name: Release and get the version

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Release based on branch
        uses: mehdi-ra/main-develop-semver@v1.5.0
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          releaseTitle: Auto release

      - name: Extract branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch

      # Docker release
      # If development release latest tag
      # If branch name release version

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: devopshobbies/kaiser-biolerplate
          tags: type=raw,value=${{ steps.release.outputs.releaseVersion }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.KAISER_DOCKERHUB_USERNAME }}
          password: ${{ secrets.KAISER_DOCKERHUB_TOKEN }}

      - name: Build and publish latest
        uses: docker/build-push-action@v4
        if: steps.extract_branch.outputs.branch == 'main' && steps.steps.release.outputs.releaseVersion != ''
        with:
          push: true
          tags: me0dira/${{ github.event.repository.name }}:latest

      - name: Build and publish pre release
        uses: docker/build-push-action@v4
        if: steps.extract_branch.outputs.branch == 'develop' && steps.steps.release.outputs.releaseVersion != ''
        with:
          push: true
          tags: me0dira/${{ github.event.repository.name }}:${{steps.release.outputs.releaseVersion}}

      - name: Build and publish pre release
        uses: docker/build-push-action@v4
        if: steps.steps.release.outputs.releaseVersion == ''
        with:
          push: true
          tags: me0dira/${{ github.event.repository.name }}:latest
